services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leetcode
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/app
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: leetcode
    depends_on:
      - db