;[pytest]
;# Your test files are inside LCxxx folders, not named *Test.py.
;# But your test functions are inside e.g. AddTwoNumbersTest.py,
;# which pytest won't find by default because the file name doesn't match.
;# To discover test functions inside *Test.py, add:
;python_files = *Test.py